
import { BASE_PATHS, PATHS_LANGUAGE } from './Paths'
import { Components } from './componentRegistry'


export const PathRedirection = [
  { auth: false, path: BASE_PATHS.HOMEPAGE, element: <Components.HomePage /> },
    { auth: false, path: PATHS_LANGUAGE.HOMEPAGE, element: <Components.HomePage /> },
  { auth: false, path: BASE_PATHS.TALKWITHASTROLOGER, element: <Components.TalkWithAstrologer /> },
  { auth: false, path: BASE_PATHS.CHATWITHASTROLOGERS, element: <Components.ChatWithAstrologer /> },
  { auth: false, path: BASE_PATHS.FREEKUNDALI, element: <Components.FreeKundali /> },
  { auth: false, path: BASE_PATHS.KUNDALI_MATCHING, element: <Components.KundaliMatching /> },
  { auth: false, path: BASE_PATHS.KUNDALI_MATCHING_REPORT, element: <Components.KundaliMatchingReport /> },
  // { auth: false, path: BASE_PATHS.HOROSCOPE, element: <Components.YearlyHoroscope /> },
  { auth: false, path: BASE_PATHS.COMPATABILITY, element: <Components.Compatibility /> },
  { auth: false, path: BASE_PATHS.PHONE_AUTH_MODALS, element: <Components.PhoneAuthModals /> },
  { auth: false, path: BASE_PATHS.FESTIVAL_CALENDER, element: <Components.FestivalCalender /> },
  { auth: false, path: BASE_PATHS.GOLD_BUYING_MUHURAT, element: <Components.GoldBuyingMuhurat /> },
  { auth: false, path: BASE_PATHS.MARRIAGE_MUHURAT, element: <Components.MarriageMuhurat /> },
  { auth: false, path: BASE_PATHS.BHUMIPUJA_MUHURAT, element: <Components.BhumiPujaMuhurat /> },
  { auth: false, path: BASE_PATHS.NAMKARAN_MUHURAT, element: <Components.NamkaranMuhurat /> },
  { auth: false, path: BASE_PATHS.CARBIKE_MUHURAT, element: <Components.CarBikeMuhurat /> },
  { auth: false, path: BASE_PATHS.OUR_ASTROLOGER, element: <Components.AstrologerListPage /> },
  { auth: false, path: BASE_PATHS.ASTROLOGER_DETAIL_PAGE, element: <Components.AstrologerDetailPage /> },
  { auth: true, path: BASE_PATHS.PROFILE_SETTING, element: <Components.ProfileSetting /> },
  { auth: false, path: BASE_PATHS.PRIVACY_POLICY, element: <Components.PrivacyPolicy /> },
  { auth: false, path: BASE_PATHS.APP_PRIVACY_POLICY, element: <Components.PrivacyPolicy /> },
  { auth: false, path: BASE_PATHS.TERMS_CONDITIONS, element: <Components.TermsAndCondition /> },
  { auth: false, path: BASE_PATHS.PAYMENT_SCREEN, element: <Components.PaymentDetails /> },
  { auth: false, path: BASE_PATHS.WEEKLY_HOROSCOPE, element: <Components.TodaysHoroscope /> },
  { auth: false, path: BASE_PATHS.WEEKLY_SINGLE_HOROSCOPE, element: <Components.YearlySingleHoroscope /> },
  { auth: false, path: BASE_PATHS.YEARLY_HOROSCOPE, element: <Components.TodaysHoroscope /> },
  { auth: false, path: BASE_PATHS.YEARLY_SINGLE_HOROSCOPE, element: <Components.YearlySingleHoroscope /> },
  { auth: false, path: BASE_PATHS.TODAYS_SINGLE_HOROSCOPE, element: <Components.YearlySingleHoroscope /> },
  { auth: false, path: BASE_PATHS.FREE_KUNDLI_KUNDLI_DETAILS_BASIC, element: <Components.FreeKundliKundliDetailsBasic /> },
  { auth: false, path: BASE_PATHS.FREE_KUNDALI_DETAILS_KP, element: <Components.FreeKundaliDetailsKp /> },
  { auth: false, path: BASE_PATHS.FREEKUNDALI_DETAILS, element: <Components.CustomTabs /> },
  { auth: false, path: BASE_PATHS.FREE_KUNDLI_KUNDLI_DETAILS_CHARTS, element: <Components.FreeKundliKundliDetailsCharts /> },
  { auth: false, path: BASE_PATHS.FREE_KUNDLIKUNDLI_DETAILS_ASHTAKVARGA, element: <Components.FreeKundliKundliDetailsAshtakvarga /> },
  { auth: false, path: BASE_PATHS.FREE_KUNDLIKUNDLI_DETAILS_DASHA_VIMSHOTTARI, element: <Components.FreeKundliKundliDetailsDashaVimshottari /> },
  { auth: false, path: BASE_PATHS.FREE_KUNDALI_DETAILS_DASHA_VIMSHOTTARI_CONTENT, element: <Components.FreeKundaliDetailsDashaVimshottariContent /> },
  { auth: false, path: BASE_PATHS.FREE_KUNDALI_REPORT, element: <Components.FreeKundaliReport /> },
  { auth: false, path: BASE_PATHS.BLOG, element: <Components.Blog /> },
  { auth: false, path: BASE_PATHS.BLOG_SINGLE_PAGE, element: <Components.BlogDetails /> },
  { auth: false, path: BASE_PATHS.ALL_HOROSCOPE, element: <Components.TodaysHoroscope /> },
  { auth: false, path: BASE_PATHS.ALL_HOROSCOPE_DETAILS, element: <Components.YearlySingleHoroscope /> },
  { auth: true, path: BASE_PATHS.TRANSACTION_WALLET, element: <Components.TransactionWallet /> },
  { auth: false, path: BASE_PATHS.ORDER_HISTORY_CALL, element: <Components.OrderHistoryCall /> },
  { auth: false, path: BASE_PATHS.SUPPORT_CHAT, element: <Components.SupportChatPage /> },
  { auth: true, path: BASE_PATHS.CHAT_SCREEN, element: <Components.ChatUI /> },
  { auth: false, path: BASE_PATHS.CHAT_ID, element: <Components.ChatUI /> },
  { auth: false, path: BASE_PATHS.TODAYS_PANCHANGAM, element: <Components.TodaysPanchang /> },
  { auth: true, path: BASE_PATHS.MONEY_WALLET, element: <Components.MoneyWallet /> },
  { auth: false, path: BASE_PATHS.PREDICTION, element: <Components.PredictionPage /> },
  { auth: false, path: BASE_PATHS.GENERAL_PREDICTION, element: <Components.PredictionPage /> },
  { auth: false, path: BASE_PATHS.NOT_FOUND, element: <Components.NotFound /> },
  { auth: false, path: BASE_PATHS.CONTACT_US, element: <Components.ContactSection /> },
  { auth: false, path: BASE_PATHS.RAHU_KAAL, element: <Components.RahuKaal /> },
  { auth: false, path: BASE_PATHS.BOOK_POOJA, element: <Components.ComingSoon /> },
  // { auth: false, path: BASE_PATHS.BOOK_POOJA, element: <Components.BookPooja /> },
  // { auth: false, path: BASE_PATHS.BOOK_POOJA_LIST, element: <Components.BookPoojaList /> },
  { auth: false, path: BASE_PATHS.BOOK_POOJA_LIST, element: <Components.ComingSoon /> },
  { auth: false, path: BASE_PATHS.ABOUT_US, element: <Components.Aboutus /> },
  { auth: false, path: BASE_PATHS.ASTRO_MALL, element: <Components.ComingSoon /> },
  { auth: false, path: BASE_PATHS.CHOGADIYA, element: <Components.Chogadiya /> },

  // ---------------------------- language ------------------------------------------------

  { auth: false, path: PATHS_LANGUAGE.TALKWITHASTROLOGER, element: <Components.TalkWithAstrologer /> },
  { auth: false, path: PATHS_LANGUAGE.CHATWITHASTROLOGERS, element: <Components.ChatWithAstrologer /> },
  { auth: false, path: PATHS_LANGUAGE.FREEKUNDALI, element: <Components.FreeKundali /> },
  { auth: false, path: PATHS_LANGUAGE.KUNDALI_MATCHING, element: <Components.KundaliMatching /> },
  { auth: false, path: PATHS_LANGUAGE.KUNDALI_MATCHING_REPORT, element: <Components.KundaliMatchingReport /> },
  // { auth: false, path: PATHS_LANGUAGE.HOROSCOPE, element: <Components.YearlyHoroscope /> },
  { auth: false, path: PATHS_LANGUAGE.COMPATABILITY, element: <Components.Compatibility /> },
  { auth: false, path: PATHS_LANGUAGE.PHONE_AUTH_MODALS, element: <Components.PhoneAuthModals /> },
  { auth: false, path: PATHS_LANGUAGE.FESTIVAL_CALENDER, element: <Components.FestivalCalender /> },
  { auth: false, path: PATHS_LANGUAGE.GOLD_BUYING_MUHURAT, element: <Components.GoldBuyingMuhurat /> },
  { auth: false, path: PATHS_LANGUAGE.MARRIAGE_MUHURAT, element: <Components.MarriageMuhurat /> },
  { auth: false, path: PATHS_LANGUAGE.BHUMIPUJA_MUHURAT, element: <Components.BhumiPujaMuhurat /> },
  { auth: false, path: PATHS_LANGUAGE.NAMKARAN_MUHURAT, element: <Components.NamkaranMuhurat /> },
  { auth: false, path: PATHS_LANGUAGE.CARBIKE_MUHURAT, element: <Components.CarBikeMuhurat /> },
  { auth: false, path: PATHS_LANGUAGE.OUR_ASTROLOGER, element: <Components.AstrologerListPage /> },
  { auth: false, path: PATHS_LANGUAGE.ASTROLOGER_DETAIL_PAGE, element: <Components.AstrologerDetailPage /> },
  { auth: true, path: PATHS_LANGUAGE.PROFILE_SETTING, element: <Components.ProfileSetting /> },
  { auth: false, path: PATHS_LANGUAGE.PRIVACY_POLICY, element: <Components.PrivacyPolicy /> },
  { auth: false, path: PATHS_LANGUAGE.APP_PRIVACY_POLICY, element: <Components.PrivacyPolicy /> },
  { auth: false, path: PATHS_LANGUAGE.TERMS_CONDITIONS, element: <Components.TermsAndCondition /> },
  { auth: false, path: PATHS_LANGUAGE.PAYMENT_SCREEN, element: <Components.PaymentDetails /> },
  { auth: false, path: PATHS_LANGUAGE.WEEKLY_HOROSCOPE, element: <Components.TodaysHoroscope /> },
  { auth: false, path: PATHS_LANGUAGE.WEEKLY_SINGLE_HOROSCOPE, element: <Components.YearlySingleHoroscope /> },
  { auth: false, path: PATHS_LANGUAGE.YEARLY_HOROSCOPE, element: <Components.TodaysHoroscope /> },
  { auth: false, path: PATHS_LANGUAGE.YEARLY_SINGLE_HOROSCOPE, element: <Components.YearlySingleHoroscope /> },
  { auth: false, path: PATHS_LANGUAGE.TODAYS_SINGLE_HOROSCOPE, element: <Components.YearlySingleHoroscope /> },
  { auth: false, path: PATHS_LANGUAGE.FREE_KUNDLI_KUNDLI_DETAILS_BASIC, element: <Components.FreeKundliKundliDetailsBasic /> },
  { auth: false, path: PATHS_LANGUAGE.FREE_KUNDALI_DETAILS_KP, element: <Components.FreeKundaliDetailsKp /> },
  { auth: false, path: PATHS_LANGUAGE.FREEKUNDALI_DETAILS, element: <Components.CustomTabs /> },
  { auth: false, path: PATHS_LANGUAGE.FREE_KUNDLI_KUNDLI_DETAILS_CHARTS, element: <Components.FreeKundliKundliDetailsCharts /> },
  { auth: false, path: PATHS_LANGUAGE.FREE_KUNDLIKUNDLI_DETAILS_ASHTAKVARGA, element: <Components.FreeKundliKundliDetailsAshtakvarga /> },
  { auth: false, path: PATHS_LANGUAGE.FREE_KUNDLIKUNDLI_DETAILS_DASHA_VIMSHOTTARI, element: <Components.FreeKundliKundliDetailsDashaVimshottari /> },
  { auth: false, path: PATHS_LANGUAGE.FREE_KUNDALI_DETAILS_DASHA_VIMSHOTTARI_CONTENT, element: <Components.FreeKundaliDetailsDashaVimshottariContent /> },
  { auth: false, path: PATHS_LANGUAGE.FREE_KUNDALI_REPORT, element: <Components.FreeKundaliReport /> },
  { auth: false, path: PATHS_LANGUAGE.BLOG, element: <Components.Blog /> },
  { auth: false, path: PATHS_LANGUAGE.BLOG_SINGLE_PAGE, element: <Components.BlogDetails /> },
  { auth: false, path: PATHS_LANGUAGE.ALL_HOROSCOPE, element: <Components.TodaysHoroscope /> },
  { auth: false, path: PATHS_LANGUAGE.ALL_HOROSCOPE_DETAILS, element: <Components.YearlySingleHoroscope /> },
  { auth: true, path: PATHS_LANGUAGE.TRANSACTION_WALLET, element: <Components.TransactionWallet /> },
  { auth: false, path: PATHS_LANGUAGE.ORDER_HISTORY_CALL, element: <Components.OrderHistoryCall /> },
  { auth: false, path: PATHS_LANGUAGE.SUPPORT_CHAT, element: <Components.SupportChatPage /> },
  { auth: true, path: PATHS_LANGUAGE.CHAT_SCREEN, element: <Components.ChatUI /> },
  { auth: false, path: PATHS_LANGUAGE.CHAT_ID, element: <Components.ChatUI /> },
  { auth: false, path: PATHS_LANGUAGE.TODAYS_PANCHANGAM, element: <Components.TodaysPanchang /> },
  { auth: true, path: PATHS_LANGUAGE.MONEY_WALLET, element: <Components.MoneyWallet /> },
  { auth: false, path: PATHS_LANGUAGE.PREDICTION, element: <Components.PredictionPage /> },
  { auth: false, path: PATHS_LANGUAGE.GENERAL_PREDICTION, element: <Components.PredictionPage /> },
  { auth: false, path: PATHS_LANGUAGE.CONTACT_US, element: <Components.ContactSection /> },
  { auth: false, path: PATHS_LANGUAGE.RAHU_KAAL, element: <Components.RahuKaal /> },
  { auth: false, path: PATHS_LANGUAGE.BOOK_POOJA, element: <Components.ComingSoon /> },
  // { auth: false, path: PATHS_LANGUAGE.BOOK_POOJA, element: <Components.BookPooja /> },
  // { auth: false, path: PATHS_LANGUAGE.BOOK_POOJA_LIST, element: <Components.BookPoojaList /> },
  { auth: false, path: PATHS_LANGUAGE.BOOK_POOJA_LIST, element: <Components.ComingSoon /> },
  { auth: false, path: PATHS_LANGUAGE.ABOUT_US, element: <Components.Aboutus /> },
  { auth: false, path: PATHS_LANGUAGE.ASTRO_MALL, element: <Components.ComingSoon /> },
  { auth: false, path: PATHS_LANGUAGE.CHOGADIYA, element: <Components.Chogadiya /> },

]
